name: Setup CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
